apiVersion: v1
kind: Namespace
metadata:
  name: quantum-hale
  labels:
    name: quantum-hale
    app: quantum-hale-drone
    version: 1.0.0
  annotations:
    description: "Quantum HALE Drone System namespace"
    maintainer: "quantum-hale-team"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quantum-hale-quota
  namespace: quantum-hale
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
    services: "20"
    pods: "20" 