# Aircraft Parameters Configuration
# ================================
#
# This file contains realistic aircraft parameters for various HALE drone types
# including Zephyr-style solar-powered aircraft and conventional HALE platforms.
#
# Author: Quantum HALE Development Team
# License: MIT

# Zephyr-style Solar-Powered HALE Drone
# Based on Airbus Zephyr S specifications
zephyr_s:
  # Physical dimensions
  wingspan: 25.0          # meters
  wing_area: 31.5         # m²
  length: 7.5             # meters
  mass_empty: 75.0        # kg
  mass_max_takeoff: 140.0 # kg
  
  # Aerodynamic coefficients
  cl_alpha: 5.73          # lift curve slope (1/rad)
  cd0: 0.015              # zero-lift drag coefficient
  oswald_efficiency: 0.85 # Oswald efficiency factor
  aspect_ratio: 19.8      # wing aspect ratio
  
  # Propulsion (electric motors)
  thrust_max: 800.0       # N (total thrust from multiple motors)
  specific_fuel_consumption: 0.0  # kg/N/s (electric - no fuel consumption)
  propeller_efficiency: 0.85
  
  # Control surfaces
  elevator_effectiveness: 0.12
  aileron_effectiveness: 0.10
  rudder_effectiveness: 0.08
  
  # Performance
  stall_speed: 12.0       # m/s
  max_speed: 35.0         # m/s
  service_ceiling: 70000  # meters (70km)
  range_max: 5000000      # meters (5000km)
  endurance_max: 2592000  # seconds (30 days)

# Conventional HALE Drone (Turboprop)
# Based on General Atomics MQ-9 Reaper specifications
hale_turboprop:
  # Physical dimensions
  wingspan: 20.0          # meters
  wing_area: 24.0         # m²
  length: 11.0            # meters
  mass_empty: 2223.0      # kg
  mass_max_takeoff: 4763.0 # kg
  
  # Aerodynamic coefficients
  cl_alpha: 5.5           # lift curve slope (1/rad)
  cd0: 0.025              # zero-lift drag coefficient
  oswald_efficiency: 0.80 # Oswald efficiency factor
  aspect_ratio: 16.7      # wing aspect ratio
  
  # Propulsion (turboprop)
  thrust_max: 12000.0     # N
  specific_fuel_consumption: 0.0003  # kg/N/s
  propeller_efficiency: 0.80
  
  # Control surfaces
  elevator_effectiveness: 0.15
  aileron_effectiveness: 0.12
  rudder_effectiveness: 0.10
  
  # Performance
  stall_speed: 25.0       # m/s
  max_speed: 120.0        # m/s
  service_ceiling: 15000  # meters (15km)
  range_max: 1000000      # meters (1000km)
  endurance_max: 43200    # seconds (12 hours)

# High-Altitude Research Aircraft
# Based on NASA ER-2 specifications
hale_research:
  # Physical dimensions
  wingspan: 31.0          # meters
  wing_area: 91.0         # m²
  length: 30.0            # meters
  mass_empty: 8000.0      # kg
  mass_max_takeoff: 14000.0 # kg
  
  # Aerodynamic coefficients
  cl_alpha: 5.8           # lift curve slope (1/rad)
  cd0: 0.020              # zero-lift drag coefficient
  oswald_efficiency: 0.88 # Oswald efficiency factor
  aspect_ratio: 10.6      # wing aspect ratio
  
  # Propulsion (jet engine)
  thrust_max: 17000.0     # N
  specific_fuel_consumption: 0.0004  # kg/N/s
  propeller_efficiency: 1.0  # jet engine
  
  # Control surfaces
  elevator_effectiveness: 0.18
  aileron_effectiveness: 0.15
  rudder_effectiveness: 0.12
  
  # Performance
  stall_speed: 30.0       # m/s
  max_speed: 200.0        # m/s
  service_ceiling: 20000  # meters (20km)
  range_max: 2000000      # meters (2000km)
  endurance_max: 28800    # seconds (8 hours)

# Lightweight Solar HALE (Experimental)
# Ultra-lightweight design for extreme endurance
solar_ultralight:
  # Physical dimensions
  wingspan: 35.0          # meters
  wing_area: 45.0         # m²
  length: 15.0            # meters
  mass_empty: 1200.0      # kg
  mass_max_takeoff: 2500.0 # kg
  
  # Aerodynamic coefficients
  cl_alpha: 5.0           # lift curve slope (1/rad)
  cd0: 0.02               # zero-lift drag coefficient
  oswald_efficiency: 0.85 # Oswald efficiency factor
  aspect_ratio: 27.0      # wing aspect ratio
  
  # Propulsion (hybrid electric)
  thrust_max: 5000.0      # N
  specific_fuel_consumption: 0.0001  # kg/N/s (very efficient)
  propeller_efficiency: 0.8
  
  # Control surfaces
  elevator_effectiveness: 0.1
  aileron_effectiveness: 0.1
  rudder_effectiveness: 0.1
  
  # Performance
  stall_speed: 25.0       # m/s
  max_speed: 120.0        # m/s
  service_ceiling: 20000  # meters (20km)
  range_max: 500000       # meters (500km)
  endurance_max: 86400    # seconds (24 hours)

# Default aircraft (used when no specific type is specified)
default:
  # Physical dimensions
  wingspan: 25.0          # meters
  wing_area: 35.0         # m²
  length: 12.0            # meters
  mass_empty: 1500.0      # kg
  mass_max_takeoff: 3000.0 # kg
  
  # Aerodynamic coefficients
  cl_alpha: 5.5           # lift curve slope (1/rad)
  cd0: 0.02               # zero-lift drag coefficient
  oswald_efficiency: 0.85 # Oswald efficiency factor
  aspect_ratio: 18.0      # wing aspect ratio
  
  # Propulsion
  thrust_max: 6000.0      # N
  specific_fuel_consumption: 0.0002  # kg/N/s
  propeller_efficiency: 0.8
  
  # Control surfaces
  elevator_effectiveness: 0.12
  aileron_effectiveness: 0.10
  rudder_effectiveness: 0.08
  
  # Performance
  stall_speed: 25.0       # m/s
  max_speed: 120.0        # m/s
  service_ceiling: 20000  # meters (20km)
  range_max: 500000       # meters (500km)
  endurance_max: 86400    # seconds (24 hours)

# PID Controller Gains for different aircraft types
# ================================================

pid_gains:
  zephyr_s:
    altitude_controller:
      kp: 0.08
      ki: 0.005
      kd: 0.03
      output_limit: 0.3
    speed_controller:
      kp: 0.15
      ki: 0.01
      kd: 0.05
      output_limit: 0.8
    heading_controller:
      kp: 0.4
      ki: 0.005
      kd: 0.08
      output_limit: 0.2
    pitch_rate_controller:
      kp: 1.5
      ki: 0.05
      kd: 0.3
      output_limit: 0.4
    roll_rate_controller:
      kp: 1.5
      ki: 0.05
      kd: 0.3
      output_limit: 0.4
    yaw_rate_controller:
      kp: 1.2
      ki: 0.03
      kd: 0.2
      output_limit: 0.25

  hale_turboprop:
    altitude_controller:
      kp: 0.12
      ki: 0.015
      kd: 0.06
      output_limit: 0.5
    speed_controller:
      kp: 0.25
      ki: 0.025
      kd: 0.12
      output_limit: 1.0
    heading_controller:
      kp: 0.6
      ki: 0.015
      kd: 0.12
      output_limit: 0.35
    pitch_rate_controller:
      kp: 2.0
      ki: 0.1
      kd: 0.5
      output_limit: 0.5
    roll_rate_controller:
      kp: 2.0
      ki: 0.1
      kd: 0.5
      output_limit: 0.5
    yaw_rate_controller:
      kp: 1.5
      ki: 0.05
      kd: 0.3
      output_limit: 0.3

  default:
    altitude_controller:
      kp: 0.1
      ki: 0.01
      kd: 0.05
      output_limit: 0.5
    speed_controller:
      kp: 0.2
      ki: 0.02
      kd: 0.1
      output_limit: 1.0
    heading_controller:
      kp: 0.5
      ki: 0.01
      kd: 0.1
      output_limit: 0.3
    pitch_rate_controller:
      kp: 2.0
      ki: 0.1
      kd: 0.5
      output_limit: 0.5
    roll_rate_controller:
      kp: 2.0
      ki: 0.1
      kd: 0.5
      output_limit: 0.5
    yaw_rate_controller:
      kp: 1.5
      ki: 0.05
      kd: 0.3
      output_limit: 0.3

# Flight envelope limits
# =====================

envelope_limits:
  zephyr_s:
    max_altitude: 70000
    min_altitude: 100
    max_airspeed: 35.0
    min_airspeed: 14.0
    max_load_factor: 2.0
    max_angle_of_attack: 12.0  # degrees

  hale_turboprop:
    max_altitude: 15000
    min_altitude: 100
    max_airspeed: 120.0
    min_airspeed: 30.0
    max_load_factor: 2.5
    max_angle_of_attack: 15.0  # degrees

  default:
    max_altitude: 20000
    min_altitude: 100
    max_airspeed: 120.0
    min_airspeed: 30.0
    max_load_factor: 2.5
    max_angle_of_attack: 15.0  # degrees 