# Simulation configuration parameters

simulation:
  name: "quantum_hale_baseline"
  duration: 3600  # seconds
  timestep: 0.1   # seconds
  real_time_factor: 1.0  # 1.0 = real-time, 2.0 = 2x speed, 0.5 = half speed
  random_seed: 42
  output_directory: "data/simulation_results"

environment:
  atmosphere:
    density_model: "exponential"
    wind_model: "turbulence"
    weather_effects: true
  
  terrain:
    type: "flat"
    altitude: 0  # meters MSL
    obstacles: []

drones:
  - id: "DRONE_001"
    type: "hale_platform"
    initial_position: [0, 0, 20000]  # x, y, z in meters
    initial_velocity: [50, 0, 0]     # vx, vy, vz in m/s
    battery_capacity: 100000         # Wh
    payload_weight: 75               # kg
    
  - id: "DRONE_002"  
    type: "hale_platform"
    initial_position: [10000, 5000, 20000]
    initial_velocity: [50, 0, 0]
    battery_capacity: 100000
    payload_weight: 50

ground_stations:
  - id: "GROUND_001"
    position: [0, 0, 100]  # x, y, z in meters
    communication_range: 200000  # meters
    
missions:
  - drone_id: "DRONE_001"
    type: "isr_patrol"
    waypoints:
      - [0, 0, 20000]
      - [50000, 0, 20000]
      - [50000, 50000, 20000]
      - [0, 50000, 20000]
    patrol_duration: 7200  # seconds
    
threats:
  jamming_sources:
    # - position: [25000, 25000, 0]
    #   frequency_range: [2.4e9, 2.5e9]  # Hz
    #   power: 50  # dBm
    #   active_time: [1800, 3600]  # start, end in seconds 